### ISSUE TITLE
Curtains

### ISSUE THREAD

**Issue by tonysprenk** [codetheweb/homebridge-tuya#5] opened 2018-08-21 14:08 UTC
Hi,

I was so happy when I saw that you made this plugin! I've been waiting for a better solution to control my Blinds/curtains in Homekit. 

I'm having an issue though;

I have everything installed properly, I managed to find the id, key, and ip of my wifi curtain switch and added the platform to my config.js file. 

The accessory is showing up in the Home app but says that it is not supported. For some reason it also shows accessories that are not specified in the config.js any more and I can not delete them in the Home app My config is as follows:

`"platforms": [

{
  "platform": "TuyaPlatform",
  "name": "TuyaPlatform",
  "devices": [
    {
      "name": "Curtain",
      "id": "0620072xxxxxxxxxxxxx",
      "key": "37537xxxxxxxxxxx",
      "ip": "85.144.187.62"
    }]
},
`

and this is a screenshot of the Home App:

![img_ec870739242a-1](https://user-images.githubusercontent.com/38426377/44406618-5a93a580-a55c-11e8-9b5a-387b694e6f24.jpeg)

The accessories circled in red showed up since I've been trying to get this to work. 

Thank you again for making this plugin!

**Comment by codetheweb** [comment] 2018-08-21 15:00
To force-delete accessories that are no longer present in your `config.json` file, you'll have to manually delete the `persist/` and `accessories/` folders under your main Homebridge folder.  How to do so varies depending on the OS you're running, but for *nix systems you should be able to 
1. `cd ~/.homebridge/`
2. `rm -rf persist/ && rm -rf accessories/`

If that doesn't fix your issue, please provide the debug output of Homebridge by running `DEBUG=* homebridge`.

**Comment by tonysprenk** [comment] 2018-08-21 15:15
Thanks for the quick reply. I wil try this solution and let you know the result when I get home in a few hours. Could this also be a solution to the accessorie not being supported or showing no reaction? Thanks again!

**Comment by codetheweb** [comment] 2018-08-21 16:05
Maybe, you'll have to try and see.

**Comment by tonysprenk** [comment] 2018-08-21 20:08
So when I got home none of my accessories were responding for some reason. I tried a few things but ended up removing the homebridge from the Home app and adding it again. Then I reinstalled hombridge-tuya and linked the curtain switch and put the credentials in my config.json. The switch shows up as a wall outlet in the home app but it is still not responding. Any ideas? should it be using the window covering service or will it always be seen as an outlet in the home app? Thanks again for all your help!

**Comment by codetheweb** [comment] 2018-08-22 00:36
The issue is this line when Homebridge is trying to get the status:
```
Accessory [Homebridge] Error getting value for Characteristic "On": Cannot read property '1' of undefined +0ms
```

This means that `homebridge-tuya` is trying to use the default control index of `1`, but it's not present on your device.

You'll have to manually get your device's "schema" to figure out the right index.  Try the below code, after installing `tuyapi` globally with `npm i tuyapi -g`:
```javascript
const TuyaDevice = require('tuyapi');

let tuya = new TuyaDevice({
  id: '<your-id>',
  key: '<your-key>'});

tuya.resolveId().then(() => {
  tuya.get({schema: true}).then(schema => {
    console.log(schema);
  });
});
```

As long as your device is a simple switch (it's all the way on, or all the way off), you should be able to find the correct index to control it.  Once you've found the index, modify your `config.json` with it like this:

```json
"platforms": [
  {
    "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "devices": [
      {
        "name": "Curtain",
        "id": "0620072xxxxxxxxxxxxx",
        "key": "37537xxxxxxxxxxx",
        "ip": "85.144.187.62",
        "dps": <found-index>
      }]
  }]
```

Also, your IP parameter looks strange.  Do you mean for it to be a WAN IP?  It should be local to your network (so start with `10` or `192`).

**Comment by tonysprenk** [comment] 2018-08-22 04:15
Thanks for the quick reply. 

Sorry to be asking such a basic question but how/where do I implement this code to get the schema? do I create a file with it or is it something I type in terminal?

The ip is what the Link Wizzard provides me but when I don't enter it manually it resolves it automatically to be 192.168.1.100.

The switch is a 3 way switch with a "up", "pause" and "down". 

Thanks again.

**Comment by codetheweb** [comment] 2018-08-22 15:42
I should probably make it more clear that the link wizard returns the WAN IP, not the LAN IP.  You should leave it out of your `config.json` or replace it with `192.168.1.100`.

For running the above code: create a file anywhere on your computer named something like `tuya.js` and paste in the code.  Then run it in a shell with `node tuya.js`.

Since it's a 3 way switch, I doubt it would work without changes to this codebase - which I'm happy to make, if you help out with testing and providing information.

**Comment by tonysprenk** [comment] 2018-08-23 07:35
Ok I left the IP out of my config.json, it seems to resolve it automatically just fine.

I've created the .js file and ran it in terminal but I'm presented with something that doesn't seem right:

![screen shot 2018-08-23 at 09 30 27](https://user-images.githubusercontent.com/38426377/44511399-b6bf0c80-a6b7-11e8-86cb-68abb8488656.png)

I would love to help with testing and providing information. Just tell me what to do. 

Thanks again for all your help.

**Comment by codetheweb** [comment] 2018-08-23 16:35
That's... odd.

Try running `node`.  It should present you with a terminal (use `CTL+C` twice to exit).  Then run `node -v` to see the version.  It should be `≥8.0.0`.

If both of those things seem to work, try running `DEBUG=* node tuya.js`.

**Comment by tonysprenk** [comment] 2018-08-23 20:31
Node version is: 10.7.0.

Running `DEBUG=* node tuya.js` results in: 

`TuyAPI Device:  +0ms
  TuyAPI { id: '06200726bcddc2ebxxxx',
  TuyAPI   key: 'c5e5a27fb90xxxxx
  TuyAPI   port: 6668,
  TuyAPI   version: 3.1,
  TuyAPI   cipher:
  TuyAPI    TuyaCipher {
  TuyAPI      cipher:
  TuyAPI       { algorithm: [Object],
  TuyAPI         mode: [Object],
  TuyAPI         blockSize: 16,
  TuyAPI         _finish: false,
  TuyAPI         _input: null,
  TuyAPI         output: null,
  TuyAPI         _op: [Function],
  TuyAPI         _decrypt: false },
  TuyAPI      decipher:
  TuyAPI       { algorithm: [Object],
  TuyAPI         mode: [Object],
  TuyAPI         blockSize: 16,
  TuyAPI         _finish: false,
  TuyAPI         _input: null,
  TuyAPI         output: null,
  TuyAPI         _op: [Function],
  TuyAPI         _decrypt: true },
  TuyAPI      version: 3.1 } } +3ms
  TuyAPI Finding IP for device 06200726bcddc2ebxxxx +9ms
  TuyAPI Received UDP message. +973ms
  TuyAPI UDP data: +2ms
  TuyAPI { ip: '192.168.1.100',
  TuyAPI   gwId: '06200726bcddc2ebxxxx',
  TuyAPI   active: 2,
  TuyAPI   ability: 0,
  TuyAPI   mode: 0,
  TuyAPI   encrypt: true,
  TuyAPI   productKey: 'rD7uqAAgQOpSxxxx',
  TuyAPI   version: '3.1' } +0ms
  TuyAPI Payload:  { gwId: '06200726bcddc2ebxxxx', devId: '06200726bcddc2ebxxxx' } +1ms
  TuyAPI Socket attempt 1 +2ms
  TuyAPI Sending this data:  000055aa000000000000000a000000467b2267774964223a223036323030373236626364646332656238333861222c226465764964223a223036323030373236626364646332656238333861227d000000000000aa55 +1ms
  TuyAPI Socket connected. +10ms
  TuyAPI Received data back: +8ms
  TuyAPI 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55 +0ms
ÏÃ¬[ûüy\¬ZÈ)Û:«`

**Comment by codetheweb** [comment] 2018-08-24 03:32
Huh.  The device's response is `json obj data unvalid`, which `tuyapi` then tries parsing as JSON, resulting in an error.  So it doesn't like what `tuyapi` is sending.

Your device is the first I've come across that apparently doesn't use the default format.  Are you able to capture a few packets with Wireshark when you're using the app?

**Comment by tonysprenk** [comment] 2018-08-24 04:34
I've just captured me opening the app, logging in, adding the device, and using the 3 configured buttons. Hope that helps, let me know if there is anything specific I should look for. 

Where should I send the .pcapng file?

Thanks!

**Comment by codetheweb** [comment] 2018-08-24 14:11
You can upload it to [CloudShark](https://www.cloudshark.org/captures/) if you're ok with it being publicly available, or send it to the email listed on my website (link is in my Github profile).

**Comment by codetheweb** [comment] 2018-08-28 15:00
Ok, here's the results after looking at the packet dump.

Since your device has three states, represented by `1`, `2`, and `3` on DPS index `1`, it's not possible to control your with this plugin at its current state.  It also won't report the correct status, as it expects a boolean value (not an integer).

I'll look into adding support for your device either in this plugin or in `tuyapi` (I'm still not sure how I should organize code between the different repos).

**Comment by tonysprenk** [comment] 2018-08-28 15:12
Thank you so much for figuring this out and for hopefully implementing a way to control this curtain switch soon! For anyone else looking for a no hassle way to control their curtains, this is the switch: http://s.aliexpress.com/MbaeqyIv

**Comment by kalu1** [comment] 2018-09-06 11:49
It is really funny, because I've been trying the same thing :-).  I hope you will figure it out. Thanks Lukas
PS. I think there is another way. Create IFTTT buttons for open, close and pause and use plugin Homebridge-IFTTT, but it is such a complicated trip.

**Comment by codetheweb** [comment] 2018-09-06 15:01
@kalu1 that would work to set the state, but unfortunately IFTTT can't get the state of devices.

**Comment by tonysprenk** [comment] 2018-10-30 12:21
any update on this? I can see there has been a lot of work on tuyapi and I like the new method of getting device credentials, however my curtain switch still doesn't work...

**Comment by codetheweb** [comment] 2018-10-30 15:14
No, sorry @tonysprenk.  I will update this plugin at some point in the future (hopefully soon) to add support for `tuyapi`'s new event-based methodology.  I'll look into adding support for other devices (heaters, bulbs, curtains) at that point.

Sorry it's been a while, I'm in college now and life is busy.

**Comment by tonysprenk** [comment] 2018-10-30 15:25
Thanks for the reply! I’m sure your busy and i’ll Wait patiently. In the meantime: would it be possible to control my device with Tuyapi and a command line? That way I could use something like homebridge-blinds-cmd to control my curtain in the home app... thanks in advance!

**Comment by codetheweb** [comment] 2018-10-30 18:08
In theory you should be able to.  Install [this tool](https://www.npmjs.com/package/@tuyapi/cli) and check the help for the set command with `tuya-cli set -h`.  You'll need to pass in custom `--set` and `--dps` parameters.

**Comment by tonysprenk** [comment] 2018-11-03 14:17
I got this to work! For my device (curtain switch) the parameters are `--set 1` is up `--set 2` is down and `--set 3` is stop on `--dps 1`. Would it be possible to add a window covering device to this plugin with that information? Thanks so much in advance!

**Comment by codetheweb** [comment] 2018-11-03 15:08
Do your curtains report the current position at all?

**Comment by tonysprenk** [comment] 2018-11-03 15:33
@GioCirque you are right. This curtain switch happens to be connected to a tube motor which sits inside the tube for a large roller blind type curtain. I have used an accessory before where you could specify the amount of time it would take the curtain to fully close or open (this can be different due to gravity pulling on the way down) and it would use that data to calculate the position of the curtain. The window covering and garage door accesory in HomeKit to my knowledge are different in the way that the garage door is rather up or down and the window covering is able to be set to a particular percentage, for example 50% being halfway closed/open. In my specific situation it would be nice to be able to set the curtain to a specific percentage but just open/closed would be a really great step in the right direction.

**Comment by codetheweb** [comment] 2018-11-03 15:37
@tonysprenk, Ok, I'll try taking a stab at making an accessory later today.

**Comment by GioCirque** [comment] 2018-11-03 15:38
Maybe @codetheweb is right and this is nearer to a modified dimmer? I’m curious to see the traffic on this. 

@tonysprenk Can you post a session of some operations from the smart life app?

**Comment by tonysprenk** [comment] 2018-11-03 15:39
https://www.npmjs.com/package/homebridge-blinds This is the plugin I have used before where you can specify the time it takes for the blinds to fully close/open.

**Comment by codetheweb** [comment] 2018-11-03 15:40
Yep, I was going to base my implementation off that since I don't have your device.

**Comment by tonysprenk** [comment] 2018-11-03 15:41
@GioCirque do you mean like a wireshark capture? I could send you the same file I sent to @codetheweb a few months ago?

**Comment by GioCirque** [comment] 2018-11-03 15:45
@tonysprenk Yes, perfect

**Comment by tonysprenk** [comment] 2018-11-03 15:50
@GioCirque do you have an email address I can send it to?

**Comment by GioCirque** [comment] 2018-11-03 15:59
@tonysprenk You can to gio@palacino.net

Let me know when you get that address so I can delete it from this public thread.

**Comment by tonysprenk** [comment] 2018-11-03 16:09
Yes got it. And sent the wireshark capture.

**Comment by tonysprenk** [comment] 2018-11-06 14:12
Let me know of there is anything I can test on my end!

**Comment by codetheweb** [comment] 2018-11-07 17:43
@tonysprenk made a PR for you to test out.

**Comment by roetsc** [comment] 2019-01-03 15:30
Hey does anybody understands this ?
When I set with the wrong key, I get a timeout but status stays the same, looks good.
When I set with the correct key, I get a timeout, but things get corrupted, does not look good.
After change state with jinvoor app, I get again the correct status.

automation@crt-srv:~/.homebridge$ tuya-cli get --id 4740565868c63ac585bd --key <correct key> --dps 1
3
automation@crt-srv:~/.homebridge$ tuya-cli set --id 4740565868c63ac585bd --key <wrong key> --dps 1 --set 2
Error: Timeout waiting for response
    at Timeout._sendTimeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:379:25)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
automation@crt-srv:~/.homebridge$ tuya-cli get --id 4740565868c63ac585bd --key <correct key> --dps 1
3
automation@crt-srv:~/.homebridge$ tuya-cli set --id 4740565868c63ac585bd --key <correct key> --dps 1 --set 2
Error: Timeout waiting for response
    at Timeout._sendTimeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:379:25)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
automation@crt-srv:~/.homebridge$ tuya-cli get --id 4740565868c63ac585bd --key <correct key> --dps 1
LðÄ¸  Þk;tÁ¦�âôÙH³î5�ÎØ�µs�O�i_

**Comment by codetheweb** [comment] 2019-01-03 17:43
PR is merged so closing this issue.

@roetsc might want to be careful not to have the app open in the background while testing.  Also, unless you omitted your key for security purposes, I don't see it.  Please open a new issue if you still need help.

**Closed by codetheweb** 2019-01-03 17:43 UTC
Labels: device-addition

**Comment by roetsc** [comment] 2019-01-07 14:41
indeed, the cut/paste removed the key.  problem is thought that if I give the wrong key, I get a timeout, looks ok, but if I give the right key, I also get a timeout and the get afterwards give noisy result. furthermore the curtains does change position. the app does not run at this moment
